== Welcome to Frege Goodness

The purpose of this book is to assemble a series of
_posts_ or _chapters_ where each chapter exposes a single characteristic of Frege.
The chapters are deliberately short. You should be able to read a complete one
while riding the commuter train or while having lunch.

The gitbook system is an ideal medium for this purpose.
You can subscribe for instant updates and get the newest content as soon
as it is available. But unlike a blog, you also have the full
series in your hand for browsing and searching.

=== For the advanced beginner

I assume that you are an _advanced beginner_. You may have
worked through the excellent books or online tutorials that
introduce the Haskell syntax that Frege builds upon.

The purpose of this book is to ignite curiosity for topics that
come after the initial steps: What can I do next?
What are typical and idiomatic ways to use Frege?
Why should I use Frege for a certain use case?
How can I make practical use of Frege in places where purely functional programming
is traditionally considered less suitable?
Where do I hit the sweet spot?

In short, it is all about using Frege to its full potential!

=== Collaboration

This book lives on github. If you have any feedback, questions, or suggestions for
improvement, please https://github.com/Dierk/FregeGoodness/issues[file an issue].

I'm also happy to take https://github.com/Dierk/FregeGoodness/pulls[pull requests] from
those who would like to contribute to the book.

=== Credits

The Frege Goodness format is inspired by @MrHaki, who runs his
Groovy-/Grails-/Gradle-
Goodness series since a long time. I follow his example for the
topic of the Frege programming language.