[[higher]]
== Parametric Polymorphism

*Parametric polymorphism* is established in mainstream programming languages for quite some time, though the term is unknown to many. For example, in Java, it goes under the name *generic types*.

The baisc idea is simple: in the declaration of functions and data (or methods and classes), types that need not be known exactly are given as *type variables* that need to be *introduced*. Later, when the function or data is used, those formal type variables are *instantiated* with concrete types (which could well be other type variables that are valid in the context).

Here is an example in Frege (that would also be valid in Haskell, of course)

.Traditional Haskell map function
[source,haskell]
----
map ∷ (a→b) → [a] → [b]   -- optional!
map f []     = []
map f (x:xs) = f x : map f xs

sqrs = map (^2) [1..10]
----

Here is an approximation of how this would look like in Java:

.Imagined Java map function
[source,java]
----
public static<A,B> List<B> map(Function<A,B> f, List<A> xxs) {
    ... details omitted ...
}

static List<Integer> sqrs = <Integer, Integer>map(
	x -> x*x, 
	Arrays.asList(1,2,3,4,5,6,7,8,9,10));
----

Despite link:src/docs/asciidoc/inference.adoc[Frege type inference] is able to infer the type of `map` entirely on its own, it is customary to provide it explicitly. (Tools like the eclipse plugin make this a one-click action.) The point is that the introduction of type variables can be implicit, and the instantiation of type variables is always invisible. Nevertheless, it can be deduced that `map` is instantiated at type `(Int→Int) → [Int] → [Int]`. But because instantiation is invisible, many Haskell and Frege programmers don't even know that it exists at all.

Whereas the Java code shows clearly both the introduction of type variables in the method declaration as well as their instantiation. To be fair, meanwhile the Java compiler can infer many of those instantiations. It needs a hint, however, where exactly it has to do that (the so called diamond operator `<>`). 

However, this chapter is not about syntactic convenience! 
It is about two concepts that belong closely to parametric polymorphism, but are rather unknown. It is about _higher ranked types_ and _higher kinded types_. It is about what is missing in the parametric polymorphism provided by Java, making generic types a *parametric polymorphism light* at best. And thus, finally, it should provide insight why projects like FunctionalJava, HighJ, JavaSlang, to name a few, are ultimatly doomed, as noble and honourable those efforts are.

